export const CHANGE_DEGREES = "CHANGE_DEGREES";
export const CHANGE_LOCATION = "CHANGE_LOCATION";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const CHANGE_WEATER_DATA = "CHANGE_WEATER_DATA"